### ISSUE TITLE
Dev Kustomize doesn't add prefix to zookeeper env variable for kafka deployment

### ISSUE THREAD

**Issue by Rhinomcd** [g1y/crime-map#44]
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
...
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
...
          
```

If namePrefix in kustomization.yaml is set, the zookeeper service dns name will be:
namePrefix-zookeeper

i.e. 

namePrefix: dev-

DNS name becomes `dev-zookeeper`

The env variable for this deployment is not updated with a name prefix.

Solutions WIP:  
1) Use service environment variables? 

 ```
DEV_ZOOKEEPER_SERVICE_HOST=10.104.242.3
DEV_ZOOKEEPER_SERVICE_PORT=2181
```
Problem: also has the namePrefix issue -- this probably isn't it

2) Is there a way to prevent the prefix from happening on resources? do we even want this? 

3) Can customize update env variable definitions somehow?
